name: Deploy

#deploy.yml은 push(pr에서 confirm merge를 하거나 진짜 push를 하거나)가 일어났을때, 진행. 나눈 이유는 pr을 날린것만으로 서버에 실행되는 파일에 변경이 일어났기 때문이다.
#pr을 confirm해야 실제 docker-compose가 실행되어, 실행되고 있는 서버버전이 바뀜.
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3



      # appleboy/ssh-action@master 액션을 사용하여 지정한 서버에 ssh로 접속하고, script를 실행합니다.
      # script의 내용은 도커의 기존 프로세스들을 제거하고, docker repo로부터 방금 위에서 push한 내용을 pull 받아 실행하는 것입니다.
      # 실행 시, docker-compose를 사용합니다.
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hanzoom-app
            docker-compose up -d
            docker image prune -f

